name: Deploy Multi-Version

on:
  push:
    branches: [ main, v1.0.0-release, v1.1.0-release ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Install dependencies
        run: npm ci

      - name: Build main version
        if: github.ref == 'refs/heads/main'
        run: npm run build
        env:
          NODE_ENV: production
          VITE_BASE_PATH: /MD/

      - name: Build v1.0.0 version
        if: github.ref == 'refs/heads/v1.0.0-release'
        run: npm run build
        env:
          NODE_ENV: production
          VITE_BASE_PATH: /MD/v1.0.0/

      - name: Build v1.1.0 version
        if: github.ref == 'refs/heads/v1.1.0-release'
        run: npm run build
        env:
          NODE_ENV: production
          VITE_BASE_PATH: /MD/v1.1.0/

      - name: Create version directory structure
        run: |
          if [ "${{ github.ref }}" = "refs/heads/v1.0.0-release" ]; then
            mkdir -p dist/v1.0.0
            cp -r dist/* dist/v1.0.0/ 2>/dev/null || true
          elif [ "${{ github.ref }}" = "refs/heads/v1.1.0-release" ]; then
            mkdir -p dist/v1.1.0
            cp -r dist/* dist/v1.1.0/ 2>/dev/null || true
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-and-deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
